import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { paiseToInr } from './format';

// House PDF style per UI_STYLE_GUIDE.md section 20: fixed corporate navy
// (not the dynamic per-company theme color), Rs. prefix (the ₹ glyph isn't
// reliable in the default PDF font), filename `{id}.pdf`.
const NAVY = [26, 54, 93];

export function exportSiteExpensesPdf({ expenses, totals, filters, generatedBy, appTimezone = 'Asia/Kolkata' }) {
  const doc = new jsPDF();

  doc.setFillColor(...NAVY);
  doc.rect(0, 0, 210, 22, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text('Neoteric Properties — Site Expenses Report', 10, 10);
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleString('en-IN', { timeZone: appTimezone })} (${appTimezone})`, 10, 17);

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(9);
  let y = 28;
  doc.text(`Sites: ${filters.siteNames?.join(', ') || 'All accessible'}`, 10, y);
  y += 5;
  doc.text(`Filters: ${filters.summary || 'None'}`, 10, y);
  y += 5;
  doc.text(`Generated by: ${generatedBy}`, 10, y);
  y += 8;

  doc.setFillColor(...NAVY);
  doc.rect(10, y, 190, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text('Summary', 12, y + 5.5);
  y += 12;

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(9);
  doc.text(`Approved Spend: Rs. ${paiseToInr(totals.approvedSpend, { withSymbol: false })}`, 12, y);
  y += 5;
  doc.text(`Pending Amount: Rs. ${paiseToInr(totals.pendingAmount, { withSymbol: false })}`, 12, y);
  y += 7;

  Object.entries(totals.categoryWise || {}).forEach(([cat, amt]) => {
    doc.text(`${cat}: Rs. ${paiseToInr(amt, { withSymbol: false })}`, 12, y);
    y += 5;
  });
  y += 3;

  const rows = expenses.map((e) => [
    e.expenseNumber,
    new Date(e.expenseDate).toLocaleDateString('en-IN'),
    e.categorySnapshot?.name || '',
    e.description,
    `Rs. ${paiseToInr(e.amountPaise, { withSymbol: false })}`,
    e.paymentMode,
    e.status,
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Number', 'Date', 'Category', 'Description', 'Amount', 'Mode', 'Status']],
    body: rows,
    headStyles: { fillColor: NAVY, textColor: 255 },
    styles: { fontSize: 8 },
    theme: 'grid',
  });

  doc.save('site-expenses-report.pdf');
}
