const PDFDocument = require('pdfkit');
const Expense = require('../models/Expense');
const { paiseToRupeesString } = require('../utils/money');
const { EXPENSE_STATUS } = require('../config/constants');
const env = require('../config/env');

async function buildReportData({ organizationId, siteIds, dateFrom, dateTo, category, status }) {
  const query = { organizationId, siteId: { $in: siteIds } };
  if (dateFrom || dateTo) {
    query.expenseDate = {};
    if (dateFrom) query.expenseDate.$gte = new Date(dateFrom);
    if (dateTo) query.expenseDate.$lte = new Date(dateTo);
  }
  if (category) query.categoryId = { $in: category };
  if (status) query.status = { $in: status };

  const expenses = await Expense.find(query)
    .sort({ siteId: 1, expenseDate: 1 })
    .populate('createdBy', 'name')
    .populate('paidByUserId', 'name')
    .populate('siteId', 'name code')
    .lean();

  const totals = {
    approvedSpend: 0,
    pendingAmount: 0,
    categoryWise: {},
  };
  for (const e of expenses) {
    if (e.status === EXPENSE_STATUS.APPROVED) totals.approvedSpend += e.amountPaise;
    if (e.status === EXPENSE_STATUS.PENDING_APPROVAL) totals.pendingAmount += e.amountPaise;
    if ([EXPENSE_STATUS.APPROVED, EXPENSE_STATUS.PENDING_APPROVAL].includes(e.status)) {
      const key = e.categorySnapshot?.name || 'Other';
      totals.categoryWise[key] = (totals.categoryWise[key] || 0) + e.amountPaise;
    }
  }
  return { expenses, totals };
}

function toCsv({ expenses, totals }) {
  const header = ['Expense Number', 'Site', 'Date', 'Category', 'Description', 'Merchant', 'Amount (Rs.)', 'Payment Mode', 'Paid By', 'Submitted By', 'Status'];
  const rows = expenses.map((e) => [
    e.expenseNumber,
    e.siteId?.name || '',
    new Date(e.expenseDate).toISOString().slice(0, 10),
    e.categorySnapshot?.name || '',
    csvEscape(e.description),
    csvEscape(e.merchant || ''),
    paiseToRupeesString(e.amountPaise),
    e.paymentMode,
    e.paidByUserId?.name || '',
    e.createdBy?.name || '',
    e.status,
  ]);
  const lines = [header.join(','), ...rows.map((r) => r.join(','))];
  lines.push('');
  lines.push(`Approved Spend,,,,,,${paiseToRupeesString(totals.approvedSpend)}`);
  lines.push(`Pending Amount,,,,,,${paiseToRupeesString(totals.pendingAmount)}`);
  lines.push(`Generated At,${new Date().toISOString()},Timezone,${env.appTimezone}`);
  return lines.join('\n');
}

function csvEscape(value) {
  const s = String(value ?? '');
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

const NAVY = '#0B1E3F';

function streamPdf({ expenses, totals }, { title, filters, generatedBy }, res) {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${title.replace(/\s+/g, '_')}.pdf"`);
  doc.pipe(res);

  doc.rect(0, 0, doc.page.width, 70).fill(NAVY);
  doc.fillColor('#FFFFFF').fontSize(18).text('Neoteric Properties — Site Expenses', 40, 22);
  doc.fontSize(10).text(title, 40, 46);

  doc.fillColor('#000000').moveDown(3);
  doc.fontSize(9).fillColor('#444444');
  doc.text(`Generated: ${new Date().toLocaleString('en-IN', { timeZone: env.appTimezone })} (${env.appTimezone})`);
  doc.text(`Sites: ${filters.siteNames?.join(', ') || 'All accessible'}`);
  doc.text(`Filters: ${filters.summary || 'None'}`);
  doc.text(`Generated by: ${generatedBy}`);
  doc.moveDown();

  doc.fillColor(NAVY).fontSize(12).text('Summary', { underline: true });
  doc.fillColor('#000000').fontSize(10);
  doc.text(`Approved Spend: Rs. ${paiseToRupeesString(totals.approvedSpend)}`);
  doc.text(`Pending Amount: Rs. ${paiseToRupeesString(totals.pendingAmount)}`);
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor(NAVY).text('Category-wise Spend', { underline: true });
  doc.fillColor('#000000');
  for (const [cat, amt] of Object.entries(totals.categoryWise)) {
    doc.text(`${cat}: Rs. ${paiseToRupeesString(amt)}`);
  }
  doc.moveDown();

  doc.fillColor(NAVY).fontSize(12).text('Expense Detail', { underline: true });
  doc.moveDown(0.3);
  const colWidths = [70, 55, 75, 140, 60, 60, 70];
  const headers = ['Number', 'Date', 'Category', 'Description', 'Amount', 'Mode', 'Status'];
  let y = doc.y;
  doc.fontSize(8).fillColor('#FFFFFF');
  let x = 40;
  doc.rect(40, y, colWidths.reduce((a, b) => a + b, 0), 16).fill(NAVY);
  doc.fillColor('#FFFFFF');
  headers.forEach((h, i) => {
    doc.text(h, x + 2, y + 4, { width: colWidths[i] - 4 });
    x += colWidths[i];
  });
  y += 16;
  doc.fillColor('#000000');

  for (const e of expenses) {
    if (y > doc.page.height - 60) {
      doc.addPage();
      y = 40;
    }
    x = 40;
    const cells = [
      e.expenseNumber,
      new Date(e.expenseDate).toISOString().slice(0, 10),
      e.categorySnapshot?.name || '',
      e.description,
      `Rs. ${paiseToRupeesString(e.amountPaise)}`,
      e.paymentMode,
      e.status,
    ];
    cells.forEach((c, i) => {
      doc.fontSize(8).text(String(c), x + 2, y + 2, { width: colWidths[i] - 4 });
      x += colWidths[i];
    });
    y += 16;
  }

  doc.end();
}

module.exports = { buildReportData, toCsv, streamPdf };
